// <auto-generated />
using System;
using ClassBooking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassBooking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ClassBooking.Domain.Users.User", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ClassBooking.Domain.Users.Student", b =>
                {
                    b.HasBaseType("ClassBooking.Domain.Users.User");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("ClassBooking.Domain.Users.Teacher", b =>
                {
                    b.HasBaseType("ClassBooking.Domain.Users.User");

                    b.Property<int>("CancellationCount")
                        .HasColumnType("int")
                        .HasColumnName("cancellation_count");

                    b.Property<int>("LateCancellationCount")
                        .HasColumnType("int")
                        .HasColumnName("late_cancellation_count");

                    b.Property<int>("NoShowCount")
                        .HasColumnType("int")
                        .HasColumnName("no_show_count");

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("ClassBooking.Domain.Users.Student", b =>
                {
                    b.HasOne("ClassBooking.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("ClassBooking.Domain.Users.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_users_id");
                });

            modelBuilder.Entity("ClassBooking.Domain.Users.Teacher", b =>
                {
                    b.HasOne("ClassBooking.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("ClassBooking.Domain.Users.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teachers_users_id");
                });
#pragma warning restore 612, 618
        }
    }
}
